#!/bin/sh

[ "$ACTION" != "add" ] && exit 0
case "$INTERFACE" in
docker*|br‑*) ;;
*) exit 0 ;;
esac

# 创建docker zone
if ! uci show firewall.docker >/dev/null 2>&1;then
    uci add firewall zone
    uci rename firewall.@zone[-1] docker
fi

uci set firewall.docker.name="docker"
uci set firewall.docker.input="ACCEPT"
uci set firewall.docker.output="ACCEPT"
uci set firewall.docker.forward="ACCEPT"
uci set firewall.docker.masq="1"

uci del firewall.docker.network
uci add_list firewall.docker.network="docker"

# 收集所有 compose br‑xxx网桥
for dev in $(ls /sys/class/net 2>/dev/null);do
    case "$dev" in
        br‑*) uci add_list firewall.docker.network="$dev" ;;
    esac
done

# docker -> wan
if ! uci show firewall.fwd_docker2wan >/dev/null 2>&1;then
    uci add firewall forwarding
    uci rename firewall.@forwarding[-1] fwd_docker2wan
fi
uci set firewall.fwd_docker2wan.src="docker"
uci set firewall.fwd_docker2wan.dest="wan"

# docker -> wan6
if ! uci show firewall.fwd_docker2wan6 >/dev/null 2>&1;then
    uci add firewall forwarding
    uci rename firewall.@forwarding[-1] fwd_docker2wan6
fi
uci set firewall.fwd_docker2wan6.src="docker"
uci set firewall.fwd_docker2wan6.dest="wan6"

# lan -> docker
if ! uci show firewall.fwd_lan2docker >/dev/null 2>&1;then
    uci add firewall forwarding
    uci rename firewall.@forwarding[-1] fwd_lan2docker
fi
uci set firewall.fwd_lan2docker.src="lan"
uci set firewall.fwd_lan2docker.dest="docker"

uci commit firewall
/etc/init.d/firewall reload >/dev/null 2>&1
